[config]
schemaVersion = "0.0.1"


[package]
namespace = "Dannyj1"
name = "Hades_II_Randomizer"
versionNumber = "1.5.0"
description = "Hades II Randomizer is a mod that randomizes certain parts of the game everytime you start a new run."
websiteUrl = "https://github.com/Dannyj1/HadesIIRandomizer/"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-DemonDaemon = "1.1.0"
SGG_Modding-ModUtil = "4.0.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
